name: tailscale
version: "1.10.2"
license: BSD-3-Clause
summary: The easiest, most secure way to use WireGuard and 2FA.
description: >
  Zero config VPN. Installs on any device in minutes, manages firewall rules for you, and works from anywhere.
icon: tailscale.png

base: core20
grade: devel
confinement: devmode
compression: lzo

layout:
  /var/lib/tailscale:
    bind: $SNAP_DATA/var/lib/tailscale

apps:
  tailscale:
    command: usr/bin/tailscale --socket /run/snap.tailscale/tailscaled.sock

  service:
    command: usr/sbin/tailscale_snap_daemon
    daemon: simple
    post-stop-command: usr/sbin/tailscaled --cleanup
    restart-condition: on-failure

parts:
  tailscale:
    plugin: dump
    source: https://pkgs.tailscale.com/stable/tailscale_${SNAPCRAFT_PROJECT_VERSION}_${SNAPCRAFT_TARGET_ARCH}.tgz
    filesets:
      no-systemd:
        - -systemd
    organize:
      tailscale: usr/bin/
      tailscaled: usr/sbin/
    stage:
      - $no-systemd

  scripts:
    plugin: dump
    source: snap/local
    organize:
      tailscale_snap_daemon: usr/sbin/
