name: tailscale
version: 1.66.4
license: BSD-3-Clause
summary: The easiest, most secure way to use WireGuard and 2FA.
description: >
  Zero config VPN. Installs on any device in minutes, manages firewall rules for you, and works from anywhere.
icon: tailscale.png

base: core22
confinement: strict
grade: stable

layout:
  /var/lib/tailscale:
    bind: $SNAP_DATA/var/lib/tailscale

apps:
  tailscale:
    command: usr/bin/tailscale --socket /run/snap.tailscale/tailscaled.sock
    plugs:
      - network

  service:
    command: usr/sbin/tailscale_snap_daemon
    daemon: simple
    post-stop-command: usr/sbin/tailscaled --cleanup
    restart-condition: on-failure
    plugs:
      - network
      - network-bind
      - network-control
      - firewall-control
      - system-observe

parts:
  tailscale:
    plugin: dump
    source: https://pkgs.tailscale.com/stable/tailscale_${SNAPCRAFT_PROJECT_VERSION}_${CRAFT_ARCH_BUILD_FOR}.tgz
    organize:
      tailscale: usr/bin/
      tailscaled: usr/sbin/
    stage:
      - -systemd
    stage-packages:
      - iproute2

  scripts:
    plugin: dump
    source: snap/local
    organize:
      tailscale_snap_daemon: usr/sbin/
